### DNS request
POST http://localhost:8000/dns
Content-Type: application/json

{
  "domain": "http://jdecool.fr"
}

### Retrieve IP
GET http://localhost:8000/ip

### Whois request
POST http://localhost:8000/whois
Content-Type: application/json

{
    "domain": "http://jdecool.fr"
}
